### ISSUE TITLE
Damage roll from chat for powers not working

### ISSUE THREAD

**Issue by stargo0se** [lipefl/swade-tools#148]
Damage roll from chat for powers is not working atm. Seems to conflict with check for minimum strength. Console shows:

```
gb.js:378 Uncaught TypeError: Cannot read properties of undefined (reading 'matchAll')
[Detected 1 package: swade-tools]
    at Module.getMinStr (gb.js:378:45)
    at ItemRoll.rollDamage (CharRoll.js:589:16)
    at ItemRoll.rollBaseDamage (ItemRoll.js:145:14)
    at RollControl.targetFunction (RollControl.js:1149:26)
    at HTMLAnchorElement.<anonymous> (RollControl.js:631:30)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
```

**Comment by lipefl** [comment]
Fixed in v1.9.10
Thanks!
