### ISSUE TITLE
[Bug] +/- Modifier-Buttons not working

### ISSUE THREAD

**Issue by Vogliadicone** [lipefl/swade-tools#273]
The plus and minus buttons on the roll card aren't working. They worked in he past, but no idea, when and why they stopped to work. This applies to all roll cards (skills, attacks and powers).
![error](https://github.com/lipefl/swade-tools/assets/119852651/af363016-3865-49b5-a597-aeb3b4b3a834)

I can reproduce the problem in a test world with only SWADE and SWADE Tools.

- Foundry VTT: 11.315 (in the OracleCloud)
- Swade System: 3.2.4
- Swade Tools 1.14.7
- Browser: Google Chrome

**Comment by Vogliadicone** [comment]
It might be connected to this bug in SWADE core or might even be the same:
https://gitlab.com/peginc/swade/-/issues/997

**Comment by Vogliadicone** [comment]
The problem also occurs with SWADE core 3.2.5. So It wasn't related to core issue 997.

**Comment by mrcomac** [comment]
I trust there is a typo

Error:
```
gb.js:97 Uncaught ReferenceError: gb is not defined
    at HTMLButtonElement.<anonymous> (gb.js:97:21)
    at HTMLDivElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

Line 97:
```
 let val=gb.realInt(input.val());
```

Fix suggestions:
```
 let val=realInt(input.val());
```

**Comment by lipefl** [comment]
Fixed in v1.14.8
Thanks!
